### ISSUE TITLE
Updating with 2019 data before next general-election

### ISSUE THREAD

**Issue by w4rner** [robcowen/voterpower#14]
Can y'all give any guidance on how to compile a similar dataset to the 2017 csv at https://github.com/robcowen/voterpower/tree/master/csv ?
I have some students who might be interested in this as a project this Spring!

**Comment by robcowen** [comment]
I can't remember exactly where I got the data source from, but I think this seems like a good place to start: https://commonslibrary.parliament.uk/research-briefings/cbp-8749/

It could be a great little project for students to update in time for the next general election. We made this as a bit of a practice project for learning Flask a few years ago, and is itself a total rip-off of a site somebody made for the 2015 election.

It hopefully shouldn't be much work at all, once you've found the matching data.

If you need any other pointers, please do let me know. I'd love to know how you get on.

**Comment by w4rner** [comment]
Hi Rob,
Looks like you've made the update to 2019 data yourself: congrats! 
Methodology wise: interesting to consider the fact that the 'wasted 1st preference' method even understates the problem, because it doesn't account for tactical voting where people vote for another party to their 1st pref.
All to say, I'm so glad you're keeping this updated as it's a vital resource for folks like me who want to help UK voters 10X their voting power with PR.
All the best,
w4rner

**Comment by robcowen** [comment]
Indeed yes, that's a good point.

I updated it a few weeks ago but haven't really promoted it very much (it got a bit of traction on Reddit at the last election).

If the polls are right, a lot of the claims in the app of whether or not a seat is safe might be garbage. Seats that show as safe Tory might actually now be marginal, and I really don't want to encourage people not to vote.
