### ISSUE TITLE
Why is voter power index greater than 1 sometimes?

### ISSUE THREAD

**Issue by alsuren** [robcowen/voterpower#9]
> In Arfon, each person's vote is worth the equivalent of 1.679 votes

It is not clear on the website why the voter power index is allowed to be greater than one on some places. From the pie graphs on your website, I would assume that it's based solely on the proportion of votes that usefully contributed to the winning party. That would make the maximum value be 0.5 though, so I'm clearly missing something.

The links away from your site don't obviously give a mathematical definition of the index. I also had a brief look around your source code and I couldn't see how that number is calculated. It seems like it is calculated by some external party and then imported via a csv file.

Do you have a mathematical definition of the voter power index?

**Comment by robcowen** [comment]
Hi David,

I recommend you read the link to the NEF report at the bottom of the page which details how they calculated the voter index. In summary:
1) For the 1983 to 2005 general elections, they compared the victory margin in a constituency to the likelihood of it flipping at the next election. There was a very strong correlation. 
2) They used this correlation to assign a probability to each seat based on previous election results, as we have done with 2017 data. The equation for this is on the readme page and there are Excel sheets in the git that show the working. 
3) This does indeed give a max value of 0.5, so this is doubled.
4) Finally, not all constituencies are the same size, so the index is weighted to the average constituency size. This means small, close seats like Arfon end up with an index greater than 1.
